openapi: "3.0.3"
info:
  title: 42_Matcha API
  version: "1.0"
servers:
  - url: https://api.server.test/v1

components:
  parameters:
    BearerAuth:
      in: header
      name: Authorization
      required: true
      schema:
        type: string
        example: "Bearer <token>"

paths:
  /auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: "user123"
              password: "password123"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        "400":
          description: Missing required fields
        "401":
          description: Incorrect email or password

  /auth/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            example:
              first_name: "test"
              last_name: "user"
              email: "user@email.com"
              username: "user123"
              password: "password123"
      responses:
        "200":
          description: Sign up successful
        "400":
          description: Invalid or missing required fields
          content:
            application/json:
              examples:
                missingFields:
                  value:
                    errorCode: 0
                    message: "Missing required fields"
                weakPassword:
                  value:
                    errorCode: 1
                    message: "Password is too weak"
        "409":
          description: User already exists

  /auth/forgot-password:
    post:
      description: Request password reset email
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "user@email.com"
      responses:
        "201":
          description: Accepted
        "400":
          description: Missing required fields
        "409":
          description: User does not exist

  /auth/reset-password:
    post:
      description: Change password after getting reset email
      requestBody:
        required: true
        content:
          application/json:
            example:
              newPassword: "oldpassword123"
              resetToken: ""
      responses:
        "200":
          description: Password changed
        "400":
          description: Invalid or missing required fields
          content:
            application/json:
              examples:
                missingFields:
                  value:
                    errorCode: 0
                    message: "Missing required fields"
                weakPassword:
                  value:
                    errorCode: 1
                    message: "Password is too weak"

  /auth/verify:
    post:
      description: Verify account after getting verification email
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Accepted

  /profile/my-profile:
    get:
      parameters:
        - $ref: "#/components/parameters/BearerAuth"
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                profile:
                  firstname: "test_first"
                  lastname: "test_last"
                  username: "test_username"
                  picture: "http://localhost:5001/image/profile.jpg"
                isProfileCompleted: true
                notifications: []

  /profile/update:
    post:
      parameters:
        - $ref: "#/components/parameters/BearerAuth"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                gender:
                  type: string
                sexualPreference:
                  type: string
                biography:
                  type: string
                profileImage:
                  type: string
                  format: base64
            encoding:
              profileImage:
                contentType: image/png, image/jpeg
      responses:
        "201":
          description: Accepted
